# Change these first
owner: little-klee # Your GitHub organization or username, where this repository lives
repo: cdnstatus # The name of this repository

sites:
  - name: NODE
    url: http://t4vm5h3s.cd3f97c3abfd.overpowered.shop:5000
  - name: SITE
    url: http://testpage.linodeserver.cf
  - name: Client Area
    url: https://cdn.yes.ga

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.yes.ga
  baseUrl: /cdnstatus
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CDN STATUS
  introTitle: "STATUS"
  introMessage: STATUS
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
